version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: chatbot-fe
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build-config/nginx-config:/etc/nginx/conf.d
      - ./build-config/certificate:/etc/letsencrypt/live
      - ./build:/usr/share/nginx/html